# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: secondPipeline 
resources:
 pipelines:
     - pipeline: previous-pipeline-trigger
       source: first-pipeline-yaml
steps:
- script: echo this is the triggered pipeline
